start-time: 2022-07-14 22:01:58.112509

Environment:
               test-name: AVLMM
            test-dirpath: /home/alain/Surelog/third_party/tests/AVLMM
           test-filepath: /home/alain/Surelog/third_party/tests/AVLMM/AVLMM.sl
       workspace-dirpath: /home/alain/Surelog
        surelog-filepath: /home/alain/Surelog/tests/NameCollisionBind/bin/surelog
      uhdm_dump-filepath: /home/alain/Surelog/tests/NameCollisionBind/third_party/UHDM/bin/uhdm-dump
          uvm-reldirpath: ../../UVM
          output-dirpath: /home/alain/Surelog/tests/NameCollisionBind/regression/AVLMM
     golden-log-filepath: /home/alain/Surelog/third_party/tests/AVLMM/AVLMM.log
    surelog-log-filepath: /home/alain/Surelog/tests/NameCollisionBind/regression/AVLMM/AVLMM.log
  uhdm-slpp_all-filepath: /home/alain/Surelog/tests/NameCollisionBind/regression/AVLMM/slpp_all/surelog.uhdm
 uhdm-slpp_unit-filepath: /home/alain/Surelog/tests/NameCollisionBind/regression/AVLMM/slpp_unit/surelog.uhdm
  uhdm-dump-log-filepath: /home/alain/Surelog/tests/NameCollisionBind/regression/AVLMM/uhdm.dump
roundtrip-output-dirpath: /home/alain/Surelog/tests/NameCollisionBind/regression/AVLMM/roundtrip
  roundtrip_log_filepath: /home/alain/Surelog/tests/NameCollisionBind/regression/AVLMM/roundtrip/roundtrip.log
                    tool: None


Snapshot ...
Found 5 files & directories


Running Surelog ...
start-time: 2022-07-14 22:01:58.113021
Loaded command line: tb.sv test_program.sv -d 0  +libext+.v   -verbose  -writepp  -parse -fileunit
Processed command line: tb.sv test_program.sv -d 0 +libext+.v -verbose -writepp -parse -fileunit -mt 0 -mp 0 -o ../../../tests/NameCollisionBind/regression/AVLMM
Launching surelog with arguments:
['/home/alain/Surelog/tests/NameCollisionBind/bin/surelog',
 'tb.sv',
 'test_program.sv',
 '-d',
 '0',
 '+libext+.v',
 '-verbose',
 '-writepp',
 '-parse',
 '-fileunit',
 '-mt',
 '0',
 '-mp',
 '0',
 '-o',
 '../../../tests/NameCollisionBind/regression/AVLMM']


Surelog threw an exception
Traceback (most recent call last):
  File "/home/alain/Surelog/scripts/regression.py", line 347, in _run_surelog
    process = subprocess.Popen(
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/alain/Surelog/tests/NameCollisionBind/bin/surelog'
end-time: 2022-07-14 22:01:58.114373 0:00:00.001352


Normalizing surelog log file /home/alain/Surelog/tests/NameCollisionBind/regression/AVLMM/AVLMM.log


Restoring pristine state ...
Found 5 files & directories


end-time: 2022-07-14 22:01:58.114710 0:00:00.002201
