start-time: 2022-07-14 22:01:58.111620

Environment:
               test-name: BitsOp
            test-dirpath: /home/alain/Surelog/tests/BitsOp
           test-filepath: /home/alain/Surelog/tests/BitsOp/BitsOp.sl
       workspace-dirpath: /home/alain/Surelog
        surelog-filepath: /home/alain/Surelog/tests/NameCollisionBind/bin/surelog
      uhdm_dump-filepath: /home/alain/Surelog/tests/NameCollisionBind/third_party/UHDM/bin/uhdm-dump
          uvm-reldirpath: ../../third_party/UVM
          output-dirpath: /home/alain/Surelog/tests/NameCollisionBind/regression/BitsOp
     golden-log-filepath: /home/alain/Surelog/tests/BitsOp/BitsOp.log
    surelog-log-filepath: /home/alain/Surelog/tests/NameCollisionBind/regression/BitsOp/BitsOp.log
  uhdm-slpp_all-filepath: /home/alain/Surelog/tests/NameCollisionBind/regression/BitsOp/slpp_all/surelog.uhdm
 uhdm-slpp_unit-filepath: /home/alain/Surelog/tests/NameCollisionBind/regression/BitsOp/slpp_unit/surelog.uhdm
  uhdm-dump-log-filepath: /home/alain/Surelog/tests/NameCollisionBind/regression/BitsOp/uhdm.dump
roundtrip-output-dirpath: /home/alain/Surelog/tests/NameCollisionBind/regression/BitsOp/roundtrip
  roundtrip_log_filepath: /home/alain/Surelog/tests/NameCollisionBind/regression/BitsOp/roundtrip/roundtrip.log
                    tool: None


Snapshot ...
Found 4 files & directories


Running Surelog ...
start-time: 2022-07-14 22:01:58.112042
Loaded command line: -fileunit -writepp -parse  -d uhdm -sv dut.sv -nobuiltin -nocache -elabuhdm -d coveruhdm
Processed command line: -fileunit -writepp -parse -d uhdm -sv dut.sv -nobuiltin -nocache -elabuhdm -d coveruhdm -mt 0 -mp 0 -o ../NameCollisionBind/regression/BitsOp
Launching surelog with arguments:
['/home/alain/Surelog/tests/NameCollisionBind/bin/surelog',
 '-fileunit',
 '-writepp',
 '-parse',
 '-d',
 'uhdm',
 '-sv',
 'dut.sv',
 '-nobuiltin',
 '-nocache',
 '-elabuhdm',
 '-d',
 'coveruhdm',
 '-mt',
 '0',
 '-mp',
 '0',
 '-o',
 '../NameCollisionBind/regression/BitsOp']


Surelog threw an exception
Traceback (most recent call last):
  File "/home/alain/Surelog/scripts/regression.py", line 347, in _run_surelog
    process = subprocess.Popen(
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/alain/Surelog/tests/NameCollisionBind/bin/surelog'
end-time: 2022-07-14 22:01:58.113286 0:00:00.001244


Normalizing surelog log file /home/alain/Surelog/tests/NameCollisionBind/regression/BitsOp/BitsOp.log


Restoring pristine state ...
Found 4 files & directories


end-time: 2022-07-14 22:01:58.118612 0:00:00.006992
