start-time: 2022-07-14 22:01:58.084043

Environment:
               test-name: 1364_2005
            test-dirpath: /home/alain/Surelog/tests/1364_2005
           test-filepath: /home/alain/Surelog/tests/1364_2005/1364_2005.sl
       workspace-dirpath: /home/alain/Surelog
        surelog-filepath: /home/alain/Surelog/tests/NameCollisionBind/bin/surelog
      uhdm_dump-filepath: /home/alain/Surelog/tests/NameCollisionBind/third_party/UHDM/bin/uhdm-dump
          uvm-reldirpath: ../../third_party/UVM
          output-dirpath: /home/alain/Surelog/tests/NameCollisionBind/regression/1364_2005
     golden-log-filepath: /home/alain/Surelog/tests/1364_2005/1364_2005.log
    surelog-log-filepath: /home/alain/Surelog/tests/NameCollisionBind/regression/1364_2005/1364_2005.log
  uhdm-slpp_all-filepath: /home/alain/Surelog/tests/NameCollisionBind/regression/1364_2005/slpp_all/surelog.uhdm
 uhdm-slpp_unit-filepath: /home/alain/Surelog/tests/NameCollisionBind/regression/1364_2005/slpp_unit/surelog.uhdm
  uhdm-dump-log-filepath: /home/alain/Surelog/tests/NameCollisionBind/regression/1364_2005/uhdm.dump
roundtrip-output-dirpath: /home/alain/Surelog/tests/NameCollisionBind/regression/1364_2005/roundtrip
  roundtrip_log_filepath: /home/alain/Surelog/tests/NameCollisionBind/regression/1364_2005/roundtrip/roundtrip.log
                    tool: None


Snapshot ...
Found 4 files & directories


Running Surelog ...
start-time: 2022-07-14 22:01:58.084912
Loaded command line: -parse -d uhdm -d coveruhdm -elabuhdm -d ast dut.v -nobuiltin
Processed command line: -parse -d uhdm -d coveruhdm -elabuhdm -d ast dut.v -nobuiltin -mt 0 -mp 0 -o ../NameCollisionBind/regression/1364_2005
Launching surelog with arguments:
['/home/alain/Surelog/tests/NameCollisionBind/bin/surelog',
 '-parse',
 '-d',
 'uhdm',
 '-d',
 'coveruhdm',
 '-elabuhdm',
 '-d',
 'ast',
 'dut.v',
 '-nobuiltin',
 '-mt',
 '0',
 '-mp',
 '0',
 '-o',
 '../NameCollisionBind/regression/1364_2005']


Surelog threw an exception
Traceback (most recent call last):
  File "/home/alain/Surelog/scripts/regression.py", line 347, in _run_surelog
    process = subprocess.Popen(
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/alain/Surelog/tests/NameCollisionBind/bin/surelog'
end-time: 2022-07-14 22:01:58.087027 0:00:00.002115


Normalizing surelog log file /home/alain/Surelog/tests/NameCollisionBind/regression/1364_2005/1364_2005.log


Restoring pristine state ...
Found 4 files & directories


end-time: 2022-07-14 22:01:58.088297 0:00:00.004254
