start-time: 2022-07-14 22:01:58.246135

Environment:
               test-name: PreprocTest
            test-dirpath: /home/alain/Surelog/tests/PreprocTest
           test-filepath: /home/alain/Surelog/tests/PreprocTest/PreprocTest.sl
       workspace-dirpath: /home/alain/Surelog
        surelog-filepath: /home/alain/Surelog/tests/NameCollisionBind/bin/surelog
      uhdm_dump-filepath: /home/alain/Surelog/tests/NameCollisionBind/third_party/UHDM/bin/uhdm-dump
          uvm-reldirpath: ../../third_party/UVM
          output-dirpath: /home/alain/Surelog/tests/NameCollisionBind/regression/PreprocTest
     golden-log-filepath: /home/alain/Surelog/tests/PreprocTest/PreprocTest.log
    surelog-log-filepath: /home/alain/Surelog/tests/NameCollisionBind/regression/PreprocTest/PreprocTest.log
  uhdm-slpp_all-filepath: /home/alain/Surelog/tests/NameCollisionBind/regression/PreprocTest/slpp_all/surelog.uhdm
 uhdm-slpp_unit-filepath: /home/alain/Surelog/tests/NameCollisionBind/regression/PreprocTest/slpp_unit/surelog.uhdm
  uhdm-dump-log-filepath: /home/alain/Surelog/tests/NameCollisionBind/regression/PreprocTest/uhdm.dump
roundtrip-output-dirpath: /home/alain/Surelog/tests/NameCollisionBind/regression/PreprocTest/roundtrip
  roundtrip_log_filepath: /home/alain/Surelog/tests/NameCollisionBind/regression/PreprocTest/roundtrip/roundtrip.log
                    tool: None


Snapshot ...
Found 12 files & directories


Running Surelog ...
start-time: 2022-07-14 22:01:58.246685
Loaded command line: bp_common_pkg.vh bp_fe_icache_pkg.vh  -I.  -parse
Processed command line: bp_common_pkg.vh bp_fe_icache_pkg.vh -I. -parse -mt 0 -mp 0 -o ../NameCollisionBind/regression/PreprocTest
Launching surelog with arguments:
['/home/alain/Surelog/tests/NameCollisionBind/bin/surelog',
 'bp_common_pkg.vh',
 'bp_fe_icache_pkg.vh',
 '-I.',
 '-parse',
 '-mt',
 '0',
 '-mp',
 '0',
 '-o',
 '../NameCollisionBind/regression/PreprocTest']


Surelog threw an exception
Traceback (most recent call last):
  File "/home/alain/Surelog/scripts/regression.py", line 347, in _run_surelog
    process = subprocess.Popen(
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/alain/Surelog/tests/NameCollisionBind/bin/surelog'
end-time: 2022-07-14 22:01:58.248099 0:00:00.001414


Normalizing surelog log file /home/alain/Surelog/tests/NameCollisionBind/regression/PreprocTest/PreprocTest.log


Restoring pristine state ...
Found 12 files & directories


end-time: 2022-07-14 22:01:58.248614 0:00:00.002479
