start-time: 2022-07-14 22:01:58.281561

Environment:
               test-name: Unsized
            test-dirpath: /home/alain/Surelog/tests/Unsized
           test-filepath: /home/alain/Surelog/tests/Unsized/Unsized.sl
       workspace-dirpath: /home/alain/Surelog
        surelog-filepath: /home/alain/Surelog/tests/NameCollisionBind/bin/surelog
      uhdm_dump-filepath: /home/alain/Surelog/tests/NameCollisionBind/third_party/UHDM/bin/uhdm-dump
          uvm-reldirpath: ../../third_party/UVM
          output-dirpath: /home/alain/Surelog/tests/NameCollisionBind/regression/Unsized
     golden-log-filepath: /home/alain/Surelog/tests/Unsized/Unsized.log
    surelog-log-filepath: /home/alain/Surelog/tests/NameCollisionBind/regression/Unsized/Unsized.log
  uhdm-slpp_all-filepath: /home/alain/Surelog/tests/NameCollisionBind/regression/Unsized/slpp_all/surelog.uhdm
 uhdm-slpp_unit-filepath: /home/alain/Surelog/tests/NameCollisionBind/regression/Unsized/slpp_unit/surelog.uhdm
  uhdm-dump-log-filepath: /home/alain/Surelog/tests/NameCollisionBind/regression/Unsized/uhdm.dump
roundtrip-output-dirpath: /home/alain/Surelog/tests/NameCollisionBind/regression/Unsized/roundtrip
  roundtrip_log_filepath: /home/alain/Surelog/tests/NameCollisionBind/regression/Unsized/roundtrip/roundtrip.log
                    tool: None


Snapshot ...
Found 4 files & directories


Running Surelog ...
start-time: 2022-07-14 22:01:58.282158
Loaded command line: -parse -d uhdm dut.sv -nobuiltin -nocache -elabuhdm -d coveruhdm
Processed command line: -parse -d uhdm dut.sv -nobuiltin -nocache -elabuhdm -d coveruhdm -mt 0 -mp 0 -o ../NameCollisionBind/regression/Unsized
Launching surelog with arguments:
['/home/alain/Surelog/tests/NameCollisionBind/bin/surelog',
 '-parse',
 '-d',
 'uhdm',
 'dut.sv',
 '-nobuiltin',
 '-nocache',
 '-elabuhdm',
 '-d',
 'coveruhdm',
 '-mt',
 '0',
 '-mp',
 '0',
 '-o',
 '../NameCollisionBind/regression/Unsized']


Surelog threw an exception
Traceback (most recent call last):
  File "/home/alain/Surelog/scripts/regression.py", line 347, in _run_surelog
    process = subprocess.Popen(
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/alain/Surelog/tests/NameCollisionBind/bin/surelog'
end-time: 2022-07-14 22:01:58.283433 0:00:00.001275


Normalizing surelog log file /home/alain/Surelog/tests/NameCollisionBind/regression/Unsized/Unsized.log


Restoring pristine state ...
Found 4 files & directories


end-time: 2022-07-14 22:01:58.284217 0:00:00.002656
